services:
  postgres:
    image: postgres:latest
    container_name: stats-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - stats_data:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    networks:
      - proxy

volumes:
  stats_data:

networks:
  proxy:
    external: true