services:
  postgres:
    image: postgres:latest
    container_name: stats-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - /etc/letsencrypt/live/postgres.api-agloft.ru/fullchain.pem:/var/lib/postgresql/fullchain.pem:ro
      - /etc/letsencrypt/live/postgres.api-agloft.ru/privkey.pem:/var/lib/postgresql/privkey.pem:ro
      - stats_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "6432:5432"
    networks:
      - proxy

volumes:
  stats_data:

networks:
  proxy:
    external: true